### ISSUE TITLE
Compile error on windows msvc 64-bit

### ISSUE THREAD

**Issue by astutecat** [myfreeweb/systemstat#10]
Hello,

In trying to compile my code, I'm getting the following:

```
Compiling systemstat v0.1.2
error[E0432]: unresolved import `self::platform::PlatformImpl`
  --> C:\Users\#####\.cargo\registry\src\github.com-1ecc6299db9ec823\systemstat-0.1.2\src\lib.rs:14:9
   |
14 | pub use self::platform::PlatformImpl as System;
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `PlatformImpl` in `platform`. Did you mean to use `Platform`?

error[E0412]: cannot find type `PlatformMemory` in this scope
  --> C:\Users\#####\.cargo\registry\src\github.com-1ecc6299db9ec823\systemstat-0.1.2\src\data.rs:92:26
   |
92 |     pub platform_memory: PlatformMemory,
   |                          ^^^^^^^^^^^^^^ not found in this scope

error: aborting due to previous error(s)

error: Could not compile `systemstat`.
```

I'm using the stable windows toolchain with MSVC, although the error also happens if I switch to the gnu toolset.

Any ideas on what could be causing this?

**Comment by myfreeweb** [comment]
Are you installing from crates.io? Windows support is only available on git master, it's not in the 0.1.2 release

**Comment by astutecat** [comment]
That is indeed the case - I am installing from crates.io.

Do you have an idea on when a release with windows support is likely to happen?

**Comment by myfreeweb** [comment]
There's not very much Windows support though — feel free to contribute more :)

**Comment by astutecat** [comment]
If I am able to, I will :)
