### ISSUE TITLE
CPU temp: Not supported

### ISSUE THREAD

**Issue by lumenier1** [myfreeweb/systemstat#121]
I just wanted to test the CPU temperature function but for some reason it doesn't work.

Macbook Pro
Mac OS 10.15.7
rustc 1.72.0 (5680fa18f 2023-08-23)
cargo 1.72.0 (103a7ff2e 2023-08-15)

Result of `cargo run --example info`:

![image](https://github.com/valpackett/systemstat/assets/23046497/81626065-0124-4eb0-8067-a080e35d9120)

**Comment by valpackett** [comment]
Thanks for your interest. Well, "not supported" is what it is… Should actually be clarified to "not implemented".

PRs welcome; I don't currently even have access to a Mac to try to work on that myself.
