### ISSUE TITLE
`platform::linux::proc_meminfo` somehow misses `VmallocTotal` on 32-bit platforms

### ISSUE THREAD

**Issue by nc7s** [myfreeweb/systemstat#126]
Hi, as we packaged the systemstat crate in Debian, 32-bit platforms failed this test (see [logs](https://buildd.debian.org/status/package.php?p=rust-systemstat)):

https://github.com/valpackett/systemstat/blob/cbd9c1638b792d1819479f0c2baa5840f65af727/src/platform/linux.rs#L198-L200

...

https://github.com/valpackett/systemstat/blob/cbd9c1638b792d1819479f0c2baa5840f65af727/src/platform/linux.rs#L253

armel, armhf and i386, which are all 32-bit, all have one item short, namely `VmallocTotal`, which is actually present in the test fixture. I'm not sure why this happens, but going to disable this test for those architectures before this is solved.

**Comment by valpackett** [comment]
Oops.. The numbers were being parsed as `usize` and the test example was larger than a 32-bit integer.  Should be fixed in 0.2.4.
