### ISSUE TITLE
Compile error on master (c27e070)

### ISSUE THREAD

**Issue by Ploppz** [myfreeweb/systemstat#13]
Compiling c27e070 on Linux:
```
   Compiling systemstat v0.1.2 (https://github.com/myfreeweb/systemstat#c27e070b)
error[E0308]: mismatched types
   --> /home/ploppz/.cargo/git/checkouts/systemstat-39467158cd685114/c27e070/src/platform/linux.rs:365:30
    |
365 |             .and_then(|data| data.parse::<f32>())
    |                              ^^^^^^^^^^^^^^^^^^^ expected struct `std::io::Error`, found struct `std::num::ParseFloatError`
    |
    = note: expected type `std::result::Result<_, std::io::Error>`
               found type `std::result::Result<f32, std::num::ParseFloatError>`

error: aborting due to previous error
```

I personally changed it to `            .and_then(|data| Ok(data.parse::<f32>().unwrap()))` because I'm not sure how to convert to another error type sensibly. It would be easier with `error_chain`, don't you think? Or at least a custom error type that encompasses `io::Error` and `num::ParseFloatError` and whatever is needed.

**Comment by myfreeweb** [comment]
Yeah, sorry, wrote that without testing yesterday. Fixed.

I'm just using `io::Result` instead of error_chain in this project to keep it simpler.
