### ISSUE TITLE
Test with winapi-rs from git

### ISSUE THREAD

**Issue by Susurrus** [myfreeweb/systemstat#14]
Winapi 0.3 is about to be released and the maintainer is looking for people to test against it as it's a large refactoring. Since I saw you were using 0.2 I'd recommend you test against the git winapi-rs version now or even better switch to the git dependency so that any issues you run into can be resolved.

**Comment by myfreeweb** [comment]
Looks like it's been released. I'm not sure where `kernel32` stuff is now, e.g. `GetTickCount64`?

**Comment by Susurrus** [comment]
See [his blog post](https://retep998.github.io/blog/winapi-0.3/) for the details.
