### ISSUE TITLE
Getting system uptime on Windows

### ISSUE THREAD

**Issue by colindean** [myfreeweb/systemstat#15]
I [read](https://stackoverflow.com/questions/10853985/programmatically-getting-system-boot-up-time-in-c-windows#10854049) that there is a WinAPI function called [GetTickCount64](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724411(v=vs.85).aspx) which "retrieves the number of milliseconds that have elapsed since the system was started."

This appears to be implemented in kernel32 as [`kernel32::GetTickCount64()`](https://retep998.github.io/doc/kernel32/fn.GetTickCount64.html) but I'm not sure that's the best thing to use. I see [`winapi::um::sysinfoapi::GetTickCount64()`](https://github.com/retep998/winapi-rs/blob/master/src/um/sysinfoapi.rs#L73) in `winapi`, too.

This could be the solution or at least a starting point for implementing [the unimplemented Windows uptime function](https://github.com/myfreeweb/systemstat/blob/master/src/platform/windows.rs#L57).

**Comment by colindean** [comment]
Minutes after submitting #16, I found crate `uptime_lib` which provides uptime in a cross-platform way, handling for linux, windows, and bsd kernels (including macos).

Its [implementation of Windows uptime](https://github.com/itchyny/uptime-rs/blob/master/src/lib.rs#L46) retrieval comports [with mine](https://github.com/myfreeweb/systemstat/pull/16/files#diff-82a07d3ef1b243c3bfb150dbff6c2f30R59), although I pass the result of GetTickCount64 to the Duration as a u64 instead of an i64.

I'll leave #16 as it stands but I think it would be wise instead to delegate handling of uptime to `uptime_lib` entirely. Its API is very clean:

```rust
    match uptime_lib::get() {
        Ok(uptime) => {
            println!("uptime: {} seconds", uptime.num_milliseconds() as f64 / 1000.0);
        }
        Err(err) => {
            eprintln!("uptime: {}", err);
            std::process::exit(1);
        }
    }
```

**Comment by myfreeweb** [comment]
Nah, I'd prefer not to add any dependencies that abstract the actual information retrieval here :) I'll merge #16.

**Comment by colindean** [comment]
Damn, I didn't see that comment until I'd already done up #17. I think using uptime_lib is the way to go, otherwise, you will probably end up duplicating its implementation…
