### ISSUE TITLE
No network stats for packets/bytes received on interfaces

### ISSUE THREAD

**Issue by rlupton20** [myfreeweb/systemstat#18]
This would be useful - I would be looking to add this functionality myself if it's deemed useful for the project.

**Comment by myfreeweb** [comment]
Yeah of course it's useful for the project!

**Comment by rlupton20** [comment]
Excellent!

My main concern is getting these statistics for linux, for which it's probably easiest (and fastest) to grab them from the in memory kernel information at `/sys/class/net/DEVICE/statistics`.

This project seems to be BSD centred, which I've only toyed with (DragonFly for a bit, for fun). Is there any similar scheme using the filesystem for network information in the world of (Free/Open)BSD which I could employ, or would a parallel version be needed using `ioctl`? If I can write it reasonably portably I will, though I have no way to test it. Otherwise, I can just do it for linux.

**Comment by myfreeweb** [comment]
The Linux code already parses `/sys` stuff using `nom`, should be easy to add another.

Other OSes will need a different implementation, you can just keep them unimplemented, like most things on windows currently: https://github.com/myfreeweb/systemstat/blob/721338adec3c60d5c979e18dae037ceeb18391ce/src/platform/windows.rs#L88-L90

I'll implement it on FreeBSD. (BTW, always kinda wanted to know how traffic stats are exposed but was too lazy to actually research that — just traced `netstat` and it's actually `sysctl`s :D)

**Comment by rlupton20** [comment]
Ok, sounds good. Yeah, I already had a little play with how to do it, and the files are just integers (with a newline), so doesn't need `nom`.

I just assumed `ioctl` without really thinking about it. Tracing on linux just seems to show `ifconfig` using `/proc/net/dev` but there we are. I might take a look in conky's source to see if it does anything interesting/smart/worth knowing.

Yeah, I won't be implementing anything for windows :). Will hopefully get cracking next week. Thanks for your input so far!
