### ISSUE TITLE
Expose iowait statistics on linux

### ISSUE THREAD

**Issue by rlupton20** [myfreeweb/systemstat#23]
I thought this was already done when I wrote #22. I'd be interested in adding it.

I'd propose adding an os-specific field to `CpuLoad` to track this quantity (since I don't believe it's readily available on BSD).

**Comment by myfreeweb** [comment]
haha no it was not done :D

Yeah, you can add `PlatformCpuLoad` like `PlatformMemory` and keep it empty on other platforms

**Comment by rlupton20** [comment]
I have a working version using gated struct fields:

```
#[derive(Debug, Clone)]
pub struct CPULoad {
    pub user: f32,
    pub nice: f32,
    pub system: f32,
    pub interrupt: f32,
    pub idle: f32,
    #[cfg(target_os = "linux")]
    pub iowait: f32,
}
```

Would this be a palatable solution? I can rework it easily enough. I think I prefer the gated solution just because the compiler does the work of checking iowait is accessible rather than processing a map, but admittedly the map permits more extensions.

**Comment by rlupton20** [comment]
In fact I'll open a MR on what I have, and we can discuss changes there :).

**Comment by myfreeweb** [comment]
That's #24 I guess, okay
