### ISSUE TITLE
Inconsistent implementation of Filesystem::files for FreeBSD and Linux

### ISSUE THREAD

**Issue by warrenfalk** [myfreeweb/systemstat#28]
FreeBSD is implemented like this:
```rust
Filesystem {
    files: self.f_files as usize - self.f_ffree as usize,
    /* ... */
}
```

Linux is implemented like this:
```rust
Filesystem {
    files: info.f_files as usize,
    /* ... */
}
```

So the same field, ```Filesystem::files```, actually has different meanings in each platform.  I assume Linux is wrong here because it isn't actually very useful to have only the capacity.  I plan to submit a PR for this

**Comment by myfreeweb** [comment]
Yeah, looking at the man pages, `f_files` appears to mean the same thing on both platforms.
