### ISSUE TITLE
Request: Add total file count and available file count to Filesystem struct

### ISSUE THREAD

**Issue by warrenfalk** [myfreeweb/systemstat#29]
Currently you can get ```Filename::files``` which holds the number files (inodes) in use for a filesystem.  (On FreeBSD; in Linux it holds the total capacity which I think may be an error, see #28 )

In order to be able to report this as a percentage of the whole, it would be nice to be able to also get the total number of files a filesystem can have (e.g. ```files_total```).

Also Linux has both "free" and "available" counts for files.  It would be nice to be able to get both numbers, as the latter is often more relevant.  Since FreeBSD doesn't seem to have "available" we could just map the same value as for "free".

So I'd like to add as follows
```rust
struct Filesystem {
    files: usize,
    files_total: usize, // definitely this
    files_avail: usize, // also this, if possible
    /* ... */
}
```

**Comment by warrenfalk** [comment]
I'm happy to submit a PR for these, but can't currently test FreeBSD

**Comment by myfreeweb** [comment]
yeah don't worry about it, I'll test it. Actually don't bother with the PR git stuff for such a trivial change, I'll do it myself
