### ISSUE TITLE
Add support for linux

### ISSUE THREAD

**Issue by antoyo** [myfreeweb/systemstat#4]
Hello.
The [network code for FreeBSD](https://github.com/myfreeweb/systemstat/blob/master/src/platform/freebsd.rs#L135-L160) also works for Linux, so that would be great to add it for Linux.
The current Linux code for the battery, however, does not work on my computer since I do not have the same files.
Perhaps there is an API similar to the one used for FreeBSD.
Thanks.

**Comment by myfreeweb** [comment]
Oh, interesting. So network just works without any modifications at all?

It's weird that battery doesn't work. Which Linux distro and kernel version are you using?

**Comment by antoyo** [comment]
Yes, just copy-paste the code for the networks from FreeBSD to Linux and the example show the networks and IP addresses.
For the battery, thought, I get the following:
```
Battery: error: No such file or directory (os error 2), AC power: true
```
I use ArchLinux, kernel: 4.10.13.

**Comment by myfreeweb** [comment]
What do you have under `/sys/class/power_supply`? Can you post the output of the `tree` command there?

**Comment by antoyo** [comment]
Here is the output of `/sys/class/power_supply/BAT0`:
```
.
├── alarm
├── capacity
├── capacity_level
├── cycle_count
├── device -> ../../../PNP0C0A:00
├── energy_full
├── energy_full_design
├── energy_now
├── manufacturer
├── model_name
├── power
│   ├── async
│   ├── autosuspend_delay_ms
│   ├── control
│   ├── runtime_active_kids
│   ├── runtime_active_time
│   ├── runtime_enabled
│   ├── runtime_status
│   ├── runtime_suspended_time
│   └── runtime_usage
├── power_now
├── present
├── serial_number
├── status
├── subsystem -> ../../../../../../../../../class/power_supply
├── technology
├── type
├── uevent
├── voltage_min_design
└── voltage_now
```

For the battery status, the code for FreeBSD does not work since `sysctlnametomib` does not exist on Linux.

**Comment by myfreeweb** [comment]
Hmmm, did they change `charge_now` to `energy_now` (and same with `_full`)? What's in these `energy` files?

Of course the FreeBSD code does not work. I don't think Linux even has any sysctls for battery status. Linux developers like to invent virtual filesystems for everything :D

**Comment by antoyo** [comment]
It looks like this is it:
**energy_now**:
```
42600000
```
**energy_full**:
```
43200000
```
After a quick search, I saw that there's `upower` that might be worth looking at.

**Comment by myfreeweb** [comment]
Sorry for the late response, was busy with stuff. Extracted network into a common `unix` module, now works on Linux and OpenBSD. Added the `energy_` thing, please test it! (I don't have battery-powered Linux devices right now.)

**Comment by antoyo** [comment]
I made some fixes in pull request #5.

Also, I noticed the memory used is not reported correctly.
The example show 2 GB used while I have only 775 MB.

**Comment by myfreeweb** [comment]
Well crap: https://stackoverflow.com/questions/349889/how-do-you-determine-the-amount-of-linux-system-ram-in-c#comment64695386_350046

> freeram in sysinfo is not what most people would call "free RAM" […] The best option is to use the MemAvailable (as opposed to MemFree) entry in /proc/meminfo instead

I wanted to avoid opening files and parsing strings as much as possible but oh well, Linux.

And `MemAvailable` only appeared [in 2014](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=34e431b0ae398fc54ea69ff85ec700722c9da773). It's not available in old kernels, the Windows Subsystem for Linux, FreeBSD's `linprocfs` (I should probably write a patch for that :D), maybe in illumos's Linux compatibility too.

I think `PlatformMemory` on Linux should just be a map of all the key-value pairs from `/proc/meminfo`, falling back to `sysinfo` if there's no `/proc/meminfo`… I'll just implement it now

**Comment by myfreeweb** [comment]
Actually `MemAvailable` "is not suitable to calculate the used memory" https://github.com/hishamhm/htop/pull/96

But anyway `/proc/meminfo` is now used, check it out :)
