### ISSUE TITLE
Cpu temp issue

### ISSUE THREAD

**Issue by FriedPandaFries** [myfreeweb/systemstat#47]
I really like your library!! I noticed there is an issue with cpu_temp()

`let sys = System::new();
let temp = sys.cpu_temp().unwrap();
println!("{:?}", temp);`

Returns

> Err(Custom { kind: Other, error: StringError("Could not parse float") })

**Comment by myfreeweb** [comment]
Are you using the git master version or the one on crates.io? (that one is half a year old, sorry)

**Comment by FriedPandaFries** [comment]
The crates.io version. That must be the issue.

**Comment by SolidTux** [comment]
Is there a specific reason why you don't publish a new version on crates.io?

**Comment by myfreeweb** [comment]
There weren't that many changes, so I didn't care enough to upload. Released 0.1.4

**Comment by SolidTux** [comment]
Thank you, that was fast 😄
