### ISSUE TITLE
Incorrect filesystem data on Raspbian

### ISSUE THREAD

**Issue by fenhl** [myfreeweb/systemstat#54]
I have used this library to write a simple [`diskspace`](https://github.com/fenhl/diskspace) utility to display available (and optionally, total) disk space. The utility works fine on Debian (and with #53, on macOS), but reports what seem to be wildly incorrect results on Raspbian. I have tested this with the following script:

```sh
diskspace --bytes; py -c 'import shutil; print(shutil.disk_usage("/").free)'
```

On my Debian server, this produced:

```
20506071040
20506071040
```

And on my MacBook:

```
55125647360
55125647360
```

On my Raspberry Pi however:

```
1290358784
9880293376
```

The `df` utility agrees with the Python script.

**Comment by myfreeweb** [comment]
9880293376 mod 2147483647 == 1290358784. This is integer wrapping.

bytesize 0.1 uses `usize`, which is 32-bit on 32-bit platforms like raspbian. We need to upgrade to 1.0 which uses `u64`.

**Comment by fenhl** [comment]
`ByteSize` doesn't implement `Sub<ByteSize>` on 1.0 anymore, so this will require an upstream patch or workaround.
