### ISSUE TITLE
Missing cast prevents compilation under 32-bit MacOS and 32-bit FreeBSD

### ISSUE THREAD

**Issue by straussdd** [myfreeweb/systemstat#56]
While implementing a CI solution for the [hunter](https://crates.io/crates/hunter) file manager, I've come across a bug in `systemstat` that prevents it from compiling under 32-bit BSD and 32-bit MacOS systems.

[chrono::NaiveDateTime::from_timestamp()](https://docs.rs/chrono/0.3.1/chrono/naive/datetime/struct.NaiveDateTime.html#method.from_timestamp) expects its `secs` parameter to always be an `i64`. However, in `/src/platform/macos.rs:Platform:boot_time()` and `/src/platform/freebsd.rs:Platform:boot_time()`, the `tv_sec` field of the `libc::timeval` struct is passed without casting it to an `i64`.

We're using the [cross](https://crates.io/crates/cross) crate by the [Rust Embedded Devices Working Group](https://github.com/rust-embedded/wg#embedded-devices-working-group) to build binaries for foreign architectures.

Here is the build log for 32-bit MacOS:
```
$ cross build --target i686-apple-darwin --release
info: downloading component 'rust-std' for 'i686-apple-darwin'
info: installing component 'rust-std' for 'i686-apple-darwin'
 51.5 MiB /  51.5 MiB (100 %)  12.4 MiB/s ETA:   0 s
   Compiling systemstat v0.1.4
error[E0308]: mismatched types
  --> /Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/systemstat-0.1.4/src/platform/macos.rs:65:68
   |
65 |         Ok(DateTime::<Utc>::from_utc(NaiveDateTime::from_timestamp(data.tv_sec, data.tv_usec as u32), Utc))
   |                                                                    ^^^^^^^^^^^ expected i64, found i32
help: you can cast an `i32` to `i64`, which will sign-extend the source value
   |
65 |         Ok(DateTime::<Utc>::from_utc(NaiveDateTime::from_timestamp(data.tv_sec.into(), data.tv_usec as u32), Utc))
   |                                                                    ^^^^^^^^^^^^^^^^^^
error: aborting due to previous error
```

Here is the build log for 32-bit FreeBSD:
```
$ cross build --target i686-unknown-freebsd --release
info: downloading component 'rust-std' for 'i686-unknown-freebsd'
info: installing component 'rust-std' for 'i686-unknown-freebsd'
 62.9 MiB /  62.9 MiB (100 %)  13.9 MiB/s ETA:   0 s
Unable to find image 'japaric/i686-unknown-freebsd:v0.1.14' locally
v0.1.14: Pulling from japaric/i686-unknown-freebsd
Status: Downloaded newer image for japaric/i686-unknown-freebsd:v0.1.14
   Compiling systemstat v0.1.4
error[E0308]: mismatched types
   --> /cargo/registry/src/github.com-1ecc6299db9ec823/systemstat-0.1.4/src/platform/freebsd.rs:109:68
    |
109 |         Ok(DateTime::<Utc>::from_utc(NaiveDateTime::from_timestamp(data.tv_sec, data.tv_usec as u32), Utc))
    |                                                                    ^^^^^^^^^^^ expected i64, found i32
help: you can cast an `i32` to `i64`, which will sign-extend the source value
    |
109 |         Ok(DateTime::<Utc>::from_utc(NaiveDateTime::from_timestamp(data.tv_sec.into(), data.tv_usec as u32), Utc))
    |                                                                    ^^^^^^^^^^^^^^^^^^
error: aborting due to previous error
```

**Comment by myfreeweb** [comment]
argh, the explicitness of conversions strikes again. Please make a pull request with the `.into()` as suggested by the compiler :)

**Comment by straussdd** [comment]
By courtesy of @rabite0: PR #57 fix compilation on 32bit macOS/FreeBSD systems
Thanks :D!

**Comment by rabite0** [comment]
Also, if you could release a new version with the fix that would be great. Currently, this issue prevents hunter from compiling on 32 bit mac/bsd systems. It would be nice if those worked out of the box.

To make your life easier I also updated the version for you. Since it's not possible to include tags in a pull request, that's probably the most I can do to help with this.

Thanks.

**Comment by straussdd** [comment]
I've tested the patched master today and it works perfectly on both MacOS and FreeBSD, so I'll close this issue.
