### ISSUE TITLE
OS Error 21 thrown when getting mounts on Windows Server 2008R2

### ISSUE THREAD

**Issue by Larisho** [myfreeweb/systemstat#58]
When executing the `System::mounts()` function on Windows Server 2008, it returns the following error:

`The device is not ready. (os error 21)`

I tried debugging the application but because this is a production machine, I am not able to install rust and therefore the backtrace generated is just a bunch of `<unknown>`s.

λ cargo --version
cargo 1.34.0 (6789d8a0a 2019-04-01)
λ rustc --version
rustc 1.34.1 (fc50f328b 2019-04-24)
Windows Version: Windows Server 2008 R2

**Comment by myfreeweb** [comment]
interesting.. can you reproduce on a local 2008 VM and/or Win7 or something?

I'm not very familiar with Windows, so I probably won't be able to help.

**Comment by Larisho** [comment]
Just reproduced on a Windows 7 Professional machine.

main.rs:
```
extern crate systemstat;

use systemstat::{System, Platform};

fn main() {
	let sys = System::new();
	
	match sys.mounts() {
		Ok(val) => println!("{:?}", val),
		Err(e) => println!("{:?}", e)
	}
}
```

Output:
`Os { code: 21, kind: Other, message: "The device is not ready." }`

I'll pull the source and see if I can isolate which winapi call causes this error

**Comment by Larisho** [comment]
Ok, so I've discovered what the problem is.
On older windows systems (2008 && Win7, afaik), the OS will return an error when it is reading an empty CDROM drive. I was thinking that if the event of an error being returned by the `GetVolumeInformationW`, you could call `GetDriveTypeW` and see if it returns `DRIVE_CDROM` and if so, just fill the `Filesystem` struct for that drive with some values indicating that has 0 avail, 0 free, and 0 total. 

I can create a PR for it, if you want to move forward with my idea. If not, that's fine too.

**Comment by myfreeweb** [comment]
Interesting! Yeah of course please do create a PR.
