### ISSUE TITLE
cpu_load doesn't supports Windows

### ISSUE THREAD

**Issue by 38** [myfreeweb/systemstat#65]
When this is called, the function only returns with an error saying it's not supported.
But I believe there's actually some way to get the idel time, system time, user time, etc with performance counter or PDH APIs.

And I think here's the example that may be useful.

http://dostf.blogspot.com/2012/02/measuure-cpu-usage-on-windows-with-pdh.html

At least windows can provide:
"Processor({index})\\% {type} Time" performance counter, and this should be exactly similar to the definitions of the value in the CpuLoad.

![image](https://user-images.githubusercontent.com/3023614/59164137-583c1100-8ac6-11e9-9faf-59d33bc29761.png)

**Comment by myfreeweb** [comment]
yeah, if you could also implement it, that would be great :)

**Comment by adumbidiot** [comment]
I started trying to implement this, but the tests keep failing since the times don't reliably add to a float close to 1 for some reason.
