### ISSUE TITLE
cargo build doesn't work

### ISSUE THREAD

**Issue by singals** [myfreeweb/systemstat#7]
Hi Team,
I am new to Rust. I just cloned the repo and did a cargo build, it fails and gives the following message on console:
`_error[E0432]: unresolved import self::platform::PlatformImpl
  --> src/lib.rs:14:9
   |
14 | pub use self::platform::PlatformImpl as System;
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no PlatformImpl in platform. Did you mean to use Platform?

error[E0412]: cannot find type PlatformMemory in this scope
  --> src/data.rs:92:26
   |
92 |     pub platform_memory: PlatformMemory,
   |                          ^^^^^^^^^^^^^^ not found in this scope

error: aborting due to previous error(s)

error: Could not compile systemstat._`

Could you please look into this?

**Comment by myfreeweb** [comment]
Looks like your operating system is not supported yet. What OS are you on?

**Comment by singals** [comment]
Mac OS Sierra

**Comment by myfreeweb** [comment]
Yeah, there's zero macOS support, as you can see it's not listed in the README. I sold all of my modern Macs, so I haven't worked on Mac support.

Feel free to contribute it! :) You'll be able to reuse some of the existing BSD support.

**Comment by singals** [comment]
@myfreeweb thanks for the clarification, will contribute to the repo. 👍
