### ISSUE TITLE
inconsistent readings vs other polling tools...

### ISSUE THREAD

**Issue by alphastrata** [myfreeweb/systemstat#72]
Hey there,

When putting the example code into a `loop` I only get 0% usage reporting.

The Idle and temp values seem to reflect what a `cat /proc/stat` and `glances` readout are giving me...

Any ideas?
![image](https://user-images.githubusercontent.com/25101888/80336996-b109c900-8893-11ea-93d0-de20c953da50.png)

Adding a video as probably it's more illustrative:
https://imgur.com/a/ybisqaa

(Manjaro Linux 64bit / Linux 5.4.34-1-MANJARO)

**Comment by myfreeweb** [comment]
Looking at the rather blurry view of the code editor in the video :) I can see that you're not using `DelayedMeasurement` correctly. The sleep should go in between acquiring the measurement (e.g. `.cpu_load_aggregate()`) and completing it with `.done()`, that's the whole point.

**Comment by alphastrata** [comment]
ahhh... yes I moved it to elsewhere in the loop without realising it'd have such an adverse effect - sorry.

> Looking at the rather blurry view of the code editor in the video :) I can see that you're not using `DelayedMeasurement` correctly. The sleep should go in between acquiring the measurement (e.g. `.cpu_load_aggregate()`) and completing it with `.done()`, that's the whole point.
