### ISSUE TITLE
Parsing error for socket statistic

### ISSUE THREAD

**Issue by fbucek** [myfreeweb/systemstat#78]
I am calling socket stat exactly like in examples

```rust
match sys.socket_stats() {
    Ok(stats) => trace!("\nSystem socket statistics: {:?}", stats),
    Err(x) => error!("\nSystem socket statistics: error: {}", x.to_string()),
}
```

It is runnning on ARM ( raspberry pi 4 ) and it worked correctly, but suddenly it gives this `Parsing Error`

```
Parsing Error: Error { input: "\nTCP: inuse 7 orphan 0 tw 5 alloc 12 mem 0\nUDP: inuse 3 mem 3\nUDPLITE: inuse 0\nRAW: inuse 0\nFRAG: inuse 0 memory 0\n", code: Tag }
```

Using this version: 
```
[[package]]
name = "systemstat"
version = "0.1.6"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "d1f726379f0c746ad672b7e932bd390b5faae073f502e37d314950ced761ac3e"
```

**Comment by myfreeweb** [comment]
@shssoichiro ping

**Comment by shssoichiro** [comment]
Can you test this with the latest version in git? I'd like to verify if this may have been fixed by https://github.com/myfreeweb/systemstat/pull/77

**Comment by myfreeweb** [comment]
#77 doesn't look like it touches the socket one

**Comment by fbucek** [comment]
Unfortunatelly I do not know how to test it is because I saw it in logs and now I do not see that. So I do know what caused it and how to reproduce it :(
